version: 1.0.1
engine: InnoDB
collation: utf8mb4_unicode_ci

tables:
  users:
    columns:
      id:
        type: INTEGER
        notnull: true
        autoincrement: true
        unique: true

      username:
        type: varchar
        length: 255
        notnull: true
        unique: true

      email:
        type: varchar
        length: 255
        notnull: true
        unique: true

      password:
        type: varchar
        length: 255
        notnull: true

      role:
        type: varchar
        length: 255
        notnull: true
        default: user

      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true
        nullable: false

      updated_at:
        type: timestamp
        defaultcurrent: true
        notnull: true
        nullable: false
