version: 1.0.0
engine: InnoDB
collation: utf8mb4_unicode_ci
tables:
  contents:
    columns:
      id:
        type: varchar
        length: 100
        notnull: true
        unique: true

      title:
        type: varchar
        length: 150
        notnull: true

      slug:
        type: varchar
        length: 150
        notnull: true
        unique: true

      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

      updated_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

    indexes:
      PRIMARY KEY: id
