version: 1.0.7
engine: InnoDB
collation: utf8mb4_unicode_ci
tables:
  articles:
    columns:
      id:
        type: varchar
        length: 100
        notnull: true
        unique: true

      title:
        type: varchar
        length: 150
        notnull: true

      category_id:
        type: varchar
        length: 100

      user_id:
        type: varchar
        length: 100
        notnull: true

      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

      updated_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

    indexes:
      PRIMARY KEY: id

  category:
    columns:

      id:
        type: INTEGER
        length: 100
        unique: true
        autoincrement: true
      
      name:
        type: varchar
        length: 150
        notnull: true

      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

      updated_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

    indexes:
      PRIMARY KEY: id
