version: 1.1.1
engine: InnoDB
collation: utf8mb4_unicode_ci
tables:
  articles:
    columns:
      id:
        type: varchar
        length: 16
        notnull: true
        unique: true

      title:
        type: varchar
        length: 150
        notnull: true

      category_id:
        type: int
        length: 10

      user_id:
        type: varchar
        length: 50
        notnull: true

      description:
        type: text

      status:
        type: tinyint

      created_at:
        type: tinyint

      updated_at:
        type: tinyint

    indexes:
      PRIMARY KEY: id

  category:
    columns:

      id:
        type: INTEGER
        length: 16
        unique: true
        autoincrement: true
      
      name:
        type: varchar
        length: 150
        notnull: true

      created_at:
        type: tinyint

      updated_at:
        type: tinyint

    indexes:
      PRIMARY KEY: id
