version: 1.0.1
engine: InnoDB
collation: utf8mb4_unicode_ci
tables:
  articles:
    columns:
      id:
        type: varchar
        length: 100
        notnull: true
        unique: true

      title:
        type: varchar
        length: 150
        notnull: true

      user_id:
        type: varchar
        length: 100
        notnull: true

      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

      updated_at:
        type: timestamp
        defaultcurrent: true
        notnull: true

    indexes:
      PRIMARY KEY: id

  categories:
    columns:
      id:
        type: varchar
        length: 100
        notnull: true
        unique: true
        
