version: 1.0.0
engine: InnoDB
collation: utf8mb4_unicode_ci

tables: 

  users:
    columns: 
      username:
        type: varchar
        length: 255
        notnull: true
        unique: true

      email:
        type: varchar
        length: 255
        notnull: true
        unique: true

      password:
        type: varchar
        length: 255
        notnull: true

      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true
        nullable: false

      updated_at:
        type: timestamp
        defaultcurrent: true
        notnull: true
        nullable: false