version: 1.0.2
engine: InnoDB
collation: utf8mb4_unicode_ci
tables: 
  m-token:
    columns: 
      id:
        type: integer
        unsigned: true
        notnull: true
        autoincrement: true
      token:
        type: varchar
        length: 255
        notnull: true
      created_at:
        type: timestamp
        defaultcurrent: true
        notnull: true
        nullable: false
    indexes:  
       PRIMARY KEY: id