
debug: true

# use AES-256-CBC to encrypt/decrypt 
# use this command to generate a key: openssl rand -hex 32
aes-key: "a3af08095b8a63cf50d35129d514ca2703c89d159963dc7a53e5766361bbc3c9"

admin: "/panel/admin"
service: module/Site
