<?php

/**
 * @package il4mb\Mpanel
 * This is main file of Mpanel
 * do not edit this file or any of its contents
 * by editing this file, you are breaking the Application
 */

namespace il4mb\Mpanel\Core;

use il4mb\Mpanel\Core\Exception\Error;
use il4mb\Mpanel\Core\Http\Request;
use il4mb\Mpanel\Core\Http\Response;
use Throwable;

const app_config = __DIR__ . "/../config/app.yml";
$config = new Config(app_config);

class App extends AppBox
{

    
    /**
     * Constructor function for initializing the class.
     * 
     * It creates instances of the EventSystem, MiddlewareStack,
     * Router, Config, Logger, and PluginManager classes.
     *
     * @return void
     */
    public function __construct()
    {

        $this->register(Error::class);
        $this->register(Template\Engine::class);
        $this->register(Http\Router::class);
        $this->register(Module\System::class);

    }


    function getDirectory()
    {

        return __DIR__;
    }


    /**
     * Runs the application.
     */
    public function run(): void
    {

        try {

            // Create a new request
            $request = new Request();
            // Send the response
            $this->sendResponse($this("http", "router")->dispatch($request));

        } catch (Throwable $e) {
            $this("exception", "error")->catch_error($e);
        }
    }





    // Method to Send HTTP Response
    protected function sendResponse(Response $response): void
    {

        $response->send();

        // Send content
        echo $response->getContent();
    }
}
